export const SCALES_ORDER = [
    // 荣格八维 (8个功能)
    'Ne', 'Ni', 'Se', 'Si', 'Fe', 'Fi', 'Te', 'Ti',
    // 可发展领域 (8个维度)
    '学习动机', '学习方式', '信息处理', '思维', '情绪', '社交沟通', '自我管理', '创造'
];

const questions = [
    { id: 18, text: '面对信息时，我会下意识地寻找其背后的深层含义或结构。', type: 'practical', func_scale: 'Ni', func_direction: 1, dev_scale: '信息处理', dev_direction: 1 },
    { id: 48, text: '我会在对话中专注于对方观点的逻辑一致性，而不太关注情感因素。', type: 'practical', func_scale: 'Ti', func_direction: 1, dev_scale: '社交沟通', dev_direction: -1 },
    { id: 58, text: '我会花很多时间沉浸在自己的想法世界里，并从中构建独特概念。', type: 'practical', func_scale: 'Ni', func_direction: 1, dev_scale: '创造', dev_direction: 1 },
    { id: 4, text: '如果学习内容太抽象，我会感到难以投入。', type: 'practical', func_scale: 'Si', func_direction: 1, dev_scale: '学习动机', dev_direction: -1 },
    { id: 15, text: '在学习复杂内容时，我会建立清晰的任务流程来帮助理解。', type: 'practical', func_scale: 'Te', func_direction: 1, dev_scale: '学习方式', dev_direction: 1 },
    { id: 55, text: '我擅长把任务拆分、安排优先级，并推动自己完成。', type: 'practical', func_scale: 'Te', func_direction: 1, dev_scale: '自我管理', dev_direction: 1 },
    { id: 36, text: '我通常依靠过去的经验来安抚或调节自己的情绪。', type: 'practical', func_scale: 'Si', func_direction: 1, dev_scale: '情绪', dev_direction: 1 },
    { id: 2, text: '当学习任务很模糊时，我仍能凭直觉坚持探索。', type: 'practical', func_scale: 'Ni', func_direction: 1, dev_scale: '学习动机', dev_direction: 1 },
    { id: 62, text: '我在创意类活动中更注重表达内在价值、情绪或个人故事。', type: 'practical', func_scale: 'Fi', func_direction: 1, dev_scale: '创造', dev_direction: 1 },
    { id: 61, text: '当进行创意合作时，我擅长从他人的情绪或反应中捕捉创意方向。', type: 'practical', func_scale: 'Fe', func_direction: 1, dev_scale: '创造', dev_direction: 1 },
    { id: 45, text: '我很容易察觉别人的情绪，并会自动调整自己的表达方式。', type: 'practical', func_scale: 'Fe', func_direction: 1, dev_scale: '社交沟通', dev_direction: 1 },
    { id: 53, text: '我在团队任务中能主动承担责任以维持整体执行进度。', type: 'practical', func_scale: 'Fe', func_direction: 1, dev_scale: '自我管理', dev_direction: 1 },
    { id: 39, text: '在情绪失控时，我会尝试用理性的方式把问题逐一分析解决。', type: 'practical', func_scale: 'Te', func_direction: 1, dev_scale: '情绪', dev_direction: -1 },
    { id: 25, text: '我喜欢探索不同的可能性和想法来解决问题。', type: 'practical', func_scale: 'Ne', func_direction: 1, dev_scale: '思维', dev_direction: 1 },
    { id: 22, text: '我会根据自己内心的价值判断来筛选哪些信息是重要的。', type: 'practical', func_scale: 'Fi', func_direction: 1, dev_scale: '信息处理', dev_direction: -1 },
    { id: 52, text: '在执行任务时，我更倾向遵循固定步骤并保持稳定节奏。', type: 'practical', func_scale: 'Si', func_direction: 1, dev_scale: '自我管理', dev_direction: 1 },
    { id: 44, text: '我更喜欢与熟悉的人互动，并依靠既有关系模式进行沟通。', type: 'practical', func_scale: 'Si', func_direction: 1, dev_scale: '社交沟通', dev_direction: -1 },
    { id: 16, text: '我会尝试拆解知识背后的逻辑结构以找到最佳学习方式。', type: 'practical', func_scale: 'Ti', func_direction: 1, dev_scale: '学习方式', dev_direction: 1 },
    { id: 69, text: '当我手机电量低时，我会紧张或立刻寻找充电器。', type: 'filler', func_scale: null, func_direction: 0, dev_scale: null, dev_direction: 0 },
    { id: 5, text: '来自他人的鼓励或认同能提升我的学习动力。', type: 'practical', func_scale: 'Fe', func_direction: 1, dev_scale: '学习动机', dev_direction: 1 },
    { id: 3, text: '遇到有趣的学习主题时，我会立刻动手尝试。', type: 'practical', func_scale: 'Se', func_direction: 1, dev_scale: '学习动机', dev_direction: 1 },
    { id: 1, text: '我会主动从课外寻找更多相关内容来扩展学习方向。', type: 'practical', func_scale: 'Ne', func_direction: 1, dev_scale: '学习动机', dev_direction: 1 },
    { id: 57, text: '我经常在没有提示的情况下主动提出全新点子。', type: 'practical', func_scale: 'Ne', func_direction: 1, dev_scale: '创造', dev_direction: 1 },
    { id: 63, text: '当创意任务需要明确目标时，我能够快速制定产出计划并推进执行。', type: 'practical', func_scale: 'Te', func_direction: 1, dev_scale: '创造', dev_direction: 1 },
    { id: 27, text: '我能迅速在不同任务或思路间切换注意力。', type: 'practical', func_scale: 'Se', func_direction: 1, dev_scale: '思维', dev_direction: 1 },
    { id: 37, text: '我对他人的情绪变化很敏感，容易受到影响。', type: 'practical', func_scale: 'Fe', func_direction: 1, dev_scale: '情绪', dev_direction: 1 },
    { id: 11, text: '我习惯通过动手或实际操作来理解学习内容。', type: 'practical', func_scale: 'Se', func_direction: 1, dev_scale: '学习方式', dev_direction: 1 },
    { id: 10, text: '我能根据长远的学习目标调整自己的学习方式。', type: 'practical', func_scale: 'Ni', func_direction: 1, dev_scale: '学习方式', dev_direction: 1 },
    { id: 20, text: '我更容易记住那些和旧经验或熟悉背景有关的信息。', type: 'practical', func_scale: 'Si', func_direction: 1, dev_scale: '信息处理', dev_direction: 1 },
    { id: 30, text: '我在决策时常依赖个人的感受和偏好，而不是逻辑或事实。', type: 'practical', func_scale: 'Fi', func_direction: 1, dev_scale: '思维', dev_direction: -1 },
    { id: 31, text: '我做决定时主要依赖逻辑分析而非直觉或情绪。', type: 'practical', func_scale: 'Te', func_direction: 1, dev_scale: '思维', dev_direction: 1 },
    { id: 68, text: '在等待排队时，我会观察周围的人或环境。', type: 'filler', func_scale: null, func_direction: 0, dev_scale: null, dev_direction: 0 },
    { id: 35, text: '我的情绪容易受到当下环境或周围刺激的影响。', type: 'practical', func_scale: 'Se', func_direction: 1, dev_scale: '情绪', dev_direction: 1 },
    { id: 59, text: '我能很快从周围的真实事物或感官刺激中获得灵感。', type: 'practical', func_scale: 'Se', func_direction: 1, dev_scale: '创造', dev_direction: 1 },
    { id: 49, text: '我会在任务开始前主动尝试不同方法，而不是按部就班。', type: 'practical', func_scale: 'Ne', func_direction: 1, dev_scale: '自我管理', dev_direction: -1 },
    { id: 28, text: '我习惯从熟悉经验中寻找解决问题的方法。', type: 'practical', func_scale: 'Si', func_direction: 1, dev_scale: '思维', dev_direction: 1 },
    { id: 17, text: '我能迅速从大量信息中看出可能的趋势或新方向。', type: 'practical', func_scale: 'Ne', func_direction: 1, dev_scale: '信息处理', dev_direction: 1 },
    { id: 46, text: '我倾向于尊重自己的内心感受，在沟通中真实地表达自己。', type: 'practical', func_scale: 'Fi', func_direction: 1, dev_scale: '社交沟通', dev_direction: 1 },
    { id: 23, text: '我会用明确的标准和步骤来整理复杂信息，确保不遗漏重点。', type: 'practical', func_scale: 'Te', func_direction: 1, dev_scale: '信息处理', dev_direction: 1 },
    { id: 47, text: '在团队沟通中，我喜欢用明确、结构化的方式分配任务或表达观点。', type: 'practical', func_scale: 'Te', func_direction: 1, dev_scale: '社交沟通', dev_direction: 1 },
    { id: 64, text: '当需要做创意产出时，我更依赖精密推理与结构，而不是灵感或直觉。', type: 'practical', func_scale: 'Ti', func_direction: 1, dev_scale: '创造', dev_direction: -1 },
    { id: 54, text: '我在自律方面非常依赖情绪状态，情绪低落时难以保持节奏。', type: 'practical', func_scale: 'Fi', func_direction: 1, dev_scale: '自我管理', dev_direction: -1 },
    { id: 60, text: '面对艺术、设计或创意任务时，我习惯依赖既有范本且很难跳脱出来。', type: 'practical', func_scale: 'Si', func_direction: 1, dev_scale: '创造', dev_direction: -1 },
    { id: 19, text: '我习惯先关注信息中最直接、最清晰的细节部分。', type: 'practical', func_scale: 'Se', func_direction: 1, dev_scale: '信息处理', dev_direction: 1 },
    { id: 7, text: '我会根据学习目标为自己规划不同阶段的动力来源。', type: 'practical', func_scale: 'Te', func_direction: 1, dev_scale: '学习动机', dev_direction: 1 },
    { id: 65, text: '我更喜欢甜味还是咸味的零食？', type: 'filler', func_scale: null, func_direction: 0, dev_scale: null, dev_direction: 0 },
    { id: 42, text: '我习惯根据对方长期的性格或动机来判断他说话的含义。', type: 'practical', func_scale: 'Ni', func_direction: 1, dev_scale: '社交沟通', dev_direction: -1 },
    { id: 12, text: '我更喜欢按照熟悉的步骤或结构进行学习。', type: 'practical', func_scale: 'Si', func_direction: 1, dev_scale: '学习方式', dev_direction: 1 },
    { id: 56, text: '我会在行动前仔细分析任务结构，以确保执行时不会偏离。', type: 'practical', func_scale: 'Ti', func_direction: 1, dev_scale: '自我管理', dev_direction: 1 },
    { id: 24, text: '我喜欢分析信息之间的逻辑关系，并将其压缩成清晰的结构。', type: 'practical', func_scale: 'Ti', func_direction: 1, dev_scale: '信息处理', dev_direction: 1 },
    { id: 38, text: '我会认真体会自己的内心情绪，并根据感觉做出调整。', type: 'practical', func_scale: 'Fi', func_direction: 1, dev_scale: '情绪', dev_direction: 1 },
    { id: 26, text: '我会根据长远的趋势和直觉来推测未来可能发生的情况。', type: 'practical', func_scale: 'Ni', func_direction: 1, dev_scale: '思维', dev_direction: 1 },
    { id: 40, text: '我会分析情绪背后的逻辑，以便更好地管理它们。', type: 'practical', func_scale: 'Ti', func_direction: 1, dev_scale: '情绪', dev_direction: -1 },
    { id: 6, text: '如果学习内容无法与我的价值感产生联系，我会很难保持兴趣。', type: 'practical', func_scale: 'Fi', func_direction: 1, dev_scale: '学习动机', dev_direction: -1 },
    { id: 34, text: '面对压力时，我会反思自己情绪背后的深层原因。', type: 'practical', func_scale: 'Ni', func_direction: 1, dev_scale: '情绪', dev_direction: -1 },
    { id: 67, text: '我通常习惯在一天中的某个固定时间休息。', type: 'filler', func_scale: null, func_direction: 0, dev_scale: null, dev_direction: 0 },
    { id: 51, text: '我常因为外部刺激或即时兴趣而偏离原计划。', type: 'practical', func_scale: 'Se', func_direction: 1, dev_scale: '自我管理', dev_direction: -1 },
    { id: 8, text: '我常常从分析问题中激发继续深入学习的动力。', type: 'practical', func_scale: 'Ti', func_direction: 1, dev_scale: '学习动机', dev_direction: 1 },
    { id: 29, text: '我会根据自己的价值判断来衡量决策的合理性。', type: 'practical', func_scale: 'Fe', func_direction: 1, dev_scale: '思维', dev_direction: -1 },
    { id: 9, text: '我会用不同来源的知识组合出新的学习方法。', type: 'practical', func_scale: 'Ne', func_direction: 1, dev_scale: '学习方式', dev_direction: 1 },
    { id: 43, text: '我会注意对方的表情、动作等即时细节，并及时做出回应。', type: 'practical', func_scale: 'Se', func_direction: 1, dev_scale: '社交沟通', dev_direction: 1 },
    { id: 32, text: '我喜欢独立分析问题，找出事情背后的原理。', type: 'practical', func_scale: 'Ti', func_direction: 1, dev_scale: '思维', dev_direction: 1 },
    { id: 66, text: '我在学习或做事时是否会注意到天气好坏？', type: 'filler', func_scale: null, func_direction: 0, dev_scale: null, dev_direction: 0 },
    { id: 70, text: '我有时会因为兴趣来临而突然想做无关的事情。', type: 'filler', func_scale: null, func_direction: 0, dev_scale: null, dev_direction: 0 },
    { id: 33, text: '当情绪低落时，我会主动寻找新的想法或活动让自己恢复状态。', type: 'practical', func_scale: 'Ne', func_direction: 1, dev_scale: '情绪', dev_direction: 1 },
    { id: 21, text: '当别人解释信息给我听时，我更容易抓住内容要点。', type: 'practical', func_scale: 'Fe', func_direction: 1, dev_scale: '信息处理', dev_direction: 1 },
    { id: 50, text: '我能为长期任务设定清晰愿景，并坚持按照规划行动。', type: 'practical', func_scale: 'Ni', func_direction: 1, dev_scale: '自我管理', dev_direction: 1 },
    { id: 14, text: '我会依照自己内心的感觉选择最合适的学习方式，而不是跟随他人。', type: 'practical', func_scale: 'Fi', func_direction: 1, dev_scale: '学习方式', dev_direction: -1 },
    { id: 13, text: '当与别人一起学习时，我的理解方式会变得更顺畅。', type: 'practical', func_scale: 'Fe', func_direction: 1, dev_scale: '学习方式', dev_direction: 1 },
    { id: 41, text: '在社交场合中，我常能提出新的话题或想法让互动继续下去。', type: 'practical', func_scale: 'Ne', func_direction: 1, dev_scale: '社交沟通', dev_direction: 1 },
];

// 将问题列表和维度顺序导出
export default questions;